version: '3.8' # specify docker-compose version
# Define the services/containers to be run
services:
    database:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        networks:
            - backend
    server: #name of the second service
        build: . # specify the directory of the Dockerfile
        container_name: server
        ports:
            - 80:3000
        restart: always
        environment:
            - MONGO_URL=mongodb://database/restapi
        depends_on:
            - database
        networks:
            - backend
networks:
    backend: