version: '3.8'
services:
    database:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        networks:
            - backend
    server:
        build: .
        container_name: server
        ports:
            - 80:3000
        restart: always
        environment:
            - MONGO_URL=mongodb://database/restapi
        depends_on:
            - database
        networks:
            - backend
networks:
    backend: